import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/customUi/Header";
import Footer from "@/components/customUi/Footer";
import ThemeProvider from "@/components/customUi/ThemeProvider";
import RootProvider from "@/components/customUi/RootProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} selection:text-black
         selection:bg-pink-300 bg-[#D6CABA] w-screen antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" >
          <RootProvider>
            {/* Navbar */}
            <Header />
            {children}

            {/* Footer Section */}
            <Footer />
          </RootProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
