import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/components/customUI/providers/ThemeProvider";
import RootProvider from "@/components/customUI/providers/RootProvider";
import AccountProvider from "@/components/customUI/providers/AccountProvider";
import { getServerSession } from "next-auth";
import authOptions from "@/app/api/(users)/auth/[...nextauth]/option"
import SubRootProvider from "@/components/customUI/providers/SubRootProvider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NOVA - Ecommerce Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable}
      selection:text-black
        overflow-x-hidden selection:bg-pink-300 text-xs dark:bg-[#121212] 
        bg-[#D6CABA] w-screen antialiased
        [&::-webkit-scrollbar]:w-1
        [&::-webkit-scrollbar-track]:bg-transparent
        [&::-webkit-scrollbar-thumb]:bg-gray-400
        [&::-webkit-scrollbar-thumb]:rounded-full
        dark:[&::-webkit-scrollbar-thumb]:bg-gray-500
        hover:[&::-webkit-scrollbar-thumb]:bg-gray-500
        dark:hover:[&::-webkit-scrollbar-thumb]:bg-gray-500
          transition-all duration-300 ease-in-out`}>

        <AccountProvider session={session}>
          <RootProvider>
            <ThemeProvider attribute="class" defaultTheme="dark">
              <SubRootProvider>
                <Toaster />
                {children}
              </SubRootProvider>
            </ThemeProvider>
          </RootProvider>
        </AccountProvider>

      </body>
    </html>
  );
}
